# Generated by Django 5.0.2 on 2024-06-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_contact_number_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=40, verbose_name='Пороль'),
        ),
    ]
