# Generated by Django 5.0.2 on 2024-06-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Сategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namec', models.CharField(max_length=80, verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static\\imagebd', verbose_name='Картинка')),
                ('info', models.TextField(blank=True, verbose_name='Описание товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('quantity', models.IntegerField(blank=True, max_length=300, null=True, verbose_name='Количество')),
                ('is_active', models.BooleanField(default=True, verbose_name='В наличии')),
                ('сategories', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='shop.сategories')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
