# Generated by Django 5.0.2 on 2024-06-03 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_kay', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя покупателя session_key')),
                ('product', models.CharField(max_length=150, verbose_name='Наименование товара')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('total_price', models.FloatField(blank=True, default=0, null=True)),
                ('user_basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.userbasket')),
            ],
        ),
    ]
