# Generated by Django 5.0.2 on 2024-06-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_productinbasket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='quantity_active',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
