# Generated by Django 5.0.2 on 2024-06-05 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_productinbasket_quantity_active'),
        ('shop', '0004_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='quantity_active',
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Наименование товара'),
        ),
    ]
