# Generated by Django 5.0.2 on 2024-06-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_productinbasket_quantity_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
