# Generated by Django 5.0.2 on 2024-06-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_productinbasket_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinbasket',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='userbasket',
            options={'verbose_name': 'Анонимный пользователь', 'verbose_name_plural': 'Анонимные пользователи'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=150, verbose_name='Телефон')),
                ('email', models.CharField(max_length=150, verbose_name='Почта')),
                ('adres', models.CharField(max_length=150, verbose_name='Адрес')),
                ('product', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='orders.productinbasket')),
            ],
            options={
                'verbose_name': 'Журнал зыказов1',
                'verbose_name_plural': 'Журнал зыказов2',
            },
        ),
    ]
