# Generated by Django 5.0.2 on 2024-06-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_productinbasket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Журнал заказов', 'verbose_name_plural': 'Журнал заказов'},
        ),
        migrations.AlterModelOptions(
            name='productinbasket',
            options={'verbose_name': 'Товары в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AlterModelOptions(
            name='userbasket',
            options={'verbose_name': 'Ключи Сессии Анонимный пользователь', 'verbose_name_plural': 'Анонимные пользователи'},
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='total_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Общая стоимость товара'),
        ),
    ]
