# Generated by Django 5.0.2 on 2024-06-15 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='orders.productinbasket'),
        ),
    ]
