# Generated by Django 5.0.2 on 2024-06-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='plant',
            new_name='product',
        ),
    ]
